/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "by_quantumquartet_quanthink_cmath_NativeMath_UtilFunctions.h"
#include "by_quantumquartet_quanthink_cmath_NativeMath_Matrix.h"
/* Header for class by_quantumquartet_quanthink_cmath_NativeMath */

#ifndef _Included_by_quantumquartet_quanthink_cmath_NativeMath_MatrixOperations
#define _Included_by_quantumquartet_quanthink_cmath_NativeMath_MatrixOperations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     by_quantumquartet_quanthink_cmath_NativeMath
 * Method:    MatrixSumC
 * Signature: (Lby/quantumquartet/quanthink/cmath/MatrixC;Lby/quantumquartet/quanthink/cmath/MatrixC;I)Lby/quantumquartet/quanthink/cmath/TimeStruct;
 */
JNIEXPORT jobject JNICALL Java_by_quantumquartet_quanthink_cmath_NativeMath_MatrixSumC
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     by_quantumquartet_quanthink_cmath_NativeMath
 * Method:    MatrixSubC
 * Signature: (Lby/quantumquartet/quanthink/cmath/MatrixC;Lby/quantumquartet/quanthink/cmath/MatrixC;I)Lby/quantumquartet/quanthink/cmath/TimeStruct;
 */
JNIEXPORT jobject JNICALL Java_by_quantumquartet_quanthink_cmath_NativeMath_MatrixSubC
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     by_quantumquartet_quanthink_cmath_NativeMath
 * Method:    MatrixMulC
 * Signature: (Lby/quantumquartet/quanthink/cmath/MatrixC;Lby/quantumquartet/quanthink/cmath/MatrixC;I)Lby/quantumquartet/quanthink/cmath/TimeStruct;
 */
JNIEXPORT jobject JNICALL Java_by_quantumquartet_quanthink_cmath_NativeMath_MatrixMulC__Lby_quantumquartet_quanthink_cmath_MatrixC_2Lby_quantumquartet_quanthink_cmath_MatrixC_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     by_quantumquartet_quanthink_cmath_NativeMath
 * Method:    MatrixMulC
 * Signature: (Lby/quantumquartet/quanthink/cmath/MatrixC;DI)Lby/quantumquartet/quanthink/cmath/TimeStruct;
 */
JNIEXPORT jobject JNICALL Java_by_quantumquartet_quanthink_cmath_NativeMath_MatrixMulC__Lby_quantumquartet_quanthink_cmath_MatrixC_2DI
  (JNIEnv *, jobject, jobject, jdouble, jint);

/*
 * Class:     by_quantumquartet_quanthink_cmath_NativeMath
 * Method:    GetTransposeMatrix
 * Signature: (Lby/quantumquartet/quanthink/cmath/MatrixC;)Lby/quantumquartet/quanthink/cmath/TimeStruct;
 */
JNIEXPORT jobject JNICALL Java_by_quantumquartet_quanthink_cmath_NativeMath_GetTransposeMatrixC
  (JNIEnv *, jobject, jobject);

/*
 * Class:     by_quantumquartet_quanthink_cmath_NativeMath
 * Method:    GetReverseMatrix
 * Signature: (Lby/quantumquartet/quanthink/cmath/MatrixC;)Lby/quantumquartet/quanthink/cmath/TimeStruct;
 */
JNIEXPORT jobject JNICALL Java_by_quantumquartet_quanthink_cmath_NativeMath_GetReverseMatrixC
  (JNIEnv *, jobject, jobject);

/*
 * Class:     by_quantumquartet_quanthink_cmath_NativeMath
 * Method:    GetDeterminantC
 * Signature: (Lby/quantumquartet/quanthink/cmath/MatrixC;I)Lby/quantumquartet/quanthink/cmath/TimeStruct;
 */
JNIEXPORT jobject JNICALL Java_by_quantumquartet_quanthink_cmath_NativeMath_GetDeterminantC
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     by_quantumquartet_quanthink_cmath_NativeMath
 * Method:    SolveSystemC
 * Signature: (Lby/quantumquartet/quanthink/cmath/MatrixC;Lby/quantumquartet/quanthink/cmath/MatrixC;I)Lby/quantumquartet/quanthink/cmath/TimeStruct;
 */
JNIEXPORT jobject JNICALL Java_by_quantumquartet_quanthink_cmath_NativeMath_SolveSystemC
  (JNIEnv *, jobject, jobject, jobject, jint);


Matrix JavaMatrixToCMatrix(JNIEnv *env,  jobject m);
#ifdef __cplusplus
}
#endif
#endif
