/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_quantumquartet_quanthink_cmath_NativeMath_BasicArithemtic */

#ifndef _Included_by_quantumquartet_quanthink_cmath_NativeMath_BasicArithemtic
#define _Included_by_quantumquartet_quanthink_cmath_NativeMath_BasicArithemtic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     by_quantumquartet_quanthink_cmath_NativeMath
 * Method:    solveExpressionC
 * Signature: (Ljava/lang/String;)Lby/quantumquartet/quanthink/cmath/TimeStruct;
 */
JNIEXPORT jobject JNICALL Java_by_quantumquartet_quanthink_cmath_NativeMath_solveExpressionC
  (JNIEnv *, jobject, jstring);

std::string SolveExpression(std::string expr);
std::string SolveMulDiv(std::string expr);
std::string SolvePow(std::string expr);
std::string SolveSumSub(std::string expr);

#ifdef __cplusplus
}
#endif
#endif
