/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class by_quantumquartet_quanthink_cmath_NativeMath_BasicArithemtic */

#ifndef _Included_by_quantumquartet_quanthink_cmath_NativeMath_Equations
#define _Included_by_quantumquartet_quanthink_cmath_NativeMath_Equations
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     by_quantumquartet_quanthink_cmath_NativeMath
 * Method:    solveExpressionC
 * Signature: (Ljava/lang/String;)Lby/quantumquartet/quanthink/cmath/TimeStruct;
 */
JNIEXPORT jobject JNICALL Java_by_quantumquartet_quanthink_cmath_NativeMath_solveEquationC
  (JNIEnv *, jobject, jstring);

std::string SolveEquation(std::string equation);
std::string SolveSquareEquation(double a, double b, double c);
std::string SolveCubeEquation(double a, double b, double c, double d);
std::string SolveQuadraticEquation(double a, double b, double c, double d, double e);
std::string SolvePentaEquation(double a, double b, double c, double d, double e, double f);
double N4Step(double x, double a, double b, double c, double d);
int SolveP4De(double* roots, double b, double c, double d);
int SolveP4Bi(double* roots, double b, double d);
double N4Step(double x, double a, double b, double c, double d);
double* CSqrt(double x, double y);
void  dblSort3(double a, double b, double c);
double FunctionF5(double x, double a, double b, double c, double d, double e);
double SolveP5_1(double a, double b, double c, double d, double e);
double SolveP5_1(double a, double b, double c, double d, double e);
double* GetEquationCoefficients(std::string equation);

#ifdef __cplusplus
}
#endif
#endif
