/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include <exception>
#include <iostream>
#include <stdexcept>
#include <limits>
#include <math.h>
#include <sstream>
#include <vector>
/* Header for class by_quantumquartet_quanthink_cmath_UtilFunctions */

#ifndef _Included_by_quantumquartet_quanthink_cmath_NativeMath_Matrix
#define _Included_by_quantumquartet_quanthink_cmath_NativeMath_Matrix
#ifdef __cplusplus
extern "C" {
#endif


class Matrix {
private:
	int rows;
	int cols;
    double** data;
public:
	    Matrix(int rows,int cols,double** data);
        void setRows(int rows);
        int* getSize();
        void setCols(int cols);
        void setData(double** data);
        double** getData();
        double getElement(int row, int column);
        void setElement(double value, int row, int column);
        double* getRow(int i);
        double* getColumn(int j);

};
#ifdef __cplusplus
}
#endif
#endif
